# This is a basic workflow to help you get started with Actions

name: Schedule

# Controls when the workflow will run
on:
  schedule:
    - cron: '* * * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    env:
      FLAPPER_URL: ${{secrets.FLAPPER_URL}}

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Show env
        run: env
      - name: Post to twitter
        run: bash ./daysleft.sh
